// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpe8LudsvIzWSmlOrT8t_JS34L_MTahE4',
    appId: '1:688031909766:web:a511a2481cf91e96afce07',
    messagingSenderId: '688031909766',
    projectId: 'authentification-6b999',
    authDomain: 'authentification-6b999.firebaseapp.com',
    storageBucket: 'authentification-6b999.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEYnk1uGquTKZWovi-4hzuGO_OYJUC-Ls',
    appId: '1:688031909766:android:fc12ce389603d8f4afce07',
    messagingSenderId: '688031909766',
    projectId: 'authentification-6b999',
    storageBucket: 'authentification-6b999.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7doATthSWoLD6Em4E5HjFRNqyqs9qLF0',
    appId: '1:688031909766:ios:f8f4b499e43cf51aafce07',
    messagingSenderId: '688031909766',
    projectId: 'authentification-6b999',
    storageBucket: 'authentification-6b999.firebasestorage.app',
    iosBundleId: 'com.example.tpAuthentification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7doATthSWoLD6Em4E5HjFRNqyqs9qLF0',
    appId: '1:688031909766:ios:f8f4b499e43cf51aafce07',
    messagingSenderId: '688031909766',
    projectId: 'authentification-6b999',
    storageBucket: 'authentification-6b999.firebasestorage.app',
    iosBundleId: 'com.example.tpAuthentification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpe8LudsvIzWSmlOrT8t_JS34L_MTahE4',
    appId: '1:688031909766:web:4bbc271eaaf9852bafce07',
    messagingSenderId: '688031909766',
    projectId: 'authentification-6b999',
    authDomain: 'authentification-6b999.firebaseapp.com',
    storageBucket: 'authentification-6b999.firebasestorage.app',
  );
}
